-- BAI TAP 1
-- Sinh viên cài đặt hoàn chỉnh bằng các câu lệnh SQL cho 2 CSDL
-- QuanLyBanHang (Phần I, câu 1 bài tập thực hành trang 3) và
-- QuanLyGiaoVu (Phần I, câu 1 bài tập thực hành trang 11).

-- PHAN 1 --
CREATE DATABASE QLBH;
USE QLBH;
--- 1.	Tạo các quan hệ và khai báo các khóa chính, khóa ngoại của quan hệ ---
-- TAO BANG KHACHHANG --
CREATE TABLE KHACHHANG
(
	MAKH char(4) NOT NULL PRIMARY KEY,
	HOTEN varchar(40),
	DCHI varchar(50),
	SODT varchar(20),
	NGSINH smalldatetime,
	DOANHSO money,
	NGDK smalldatetime
)

-- TAO BANG NHANVIEN --
CREATE TABLE NHANVIEN
(
	MANV char(4) NOT NULL PRIMARY KEY,
	HOTEN varchar(40),
	SODT varchar(20),
	NGVL smalldatetime
)

-- TAO BANG SANPHAM --
CREATE TABLE SANPHAM
(
	MASP char(4) NOT NULL PRIMARY KEY,
	TENSP varchar(40),
	DVT varchar(20),
	NUOCSX varchar(40),
	GIA money
)

-- TAO BANG HOADON --
CREATE TABLE HOADON
(
	SOHD int NOT NULL PRIMARY KEY,
	NGHD smalldatetime,
	MAKH char(4) NOT NULL FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
	MANV char(4) NOT NULL FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
	TRIGIA money
)

-- TAO BANG CHITIETHOADON --
CREATE TABLE CTHD
(
	SOHD int,
	MASP char(4) NOT NULL FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
	SL int,
)


-- Tao DB
CREATE DATABASE QLGV;
USE QLGV;
-- KHOA --
CREATE TABLE KHOA
(
	MAKHOA varchar(4) PRIMARY KEY,
	TENKHOA varchar(40),
	NGTLAP smalldatetime,
	TRGKHOA char(4)
);
-- MONHOC --
CREATE TABLE MONHOC (
	MAMH varchar(10) PRIMARY KEY,
	TENMH varchar(40),
	TCLT tinyint,
	TCTH tinyint,
	MAKHOA varchar(4) FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
);

-- DIEUKIEN -- 
CREATE TABLE DIEUKIEN
(
	MAMH varchar(10) FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH),
	MAMH_TRUOC varchar(10) FOREIGN KEY (MAMH_TRUOC) REFERENCES MONHOC(MAMH),
	PRIMARY KEY (MAMH, MAMH_TRUOC)
);

-- GIAOVIEN --
CREATE TABLE GIAOVIEN
(
	MAGV char(4) PRIMARY KEY,
	HOTEN varchar(40),
	HOCVI varchar(10),
	HOCHAM varchar(10),
	GIOITINH varchar(3),
	NGSINH smalldatetime,
	NGVL smalldatetime,
	HESO numeric(4,2),
	MUCLUONG money,
	MAKHOA varchar(4) FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
);
-- LOP --
CREATE TABLE LOP
(
	MALOP char(3) PRIMARY KEY,
	TENLOP varchar(40),
	TRGLOP char(5),
	SISO tinyint,
	MAGVCN char(4)  FOREIGN KEY (MAGVCN) REFERENCES GIAOVIEN(MAGV)
)
-- HOCVIEN --
CREATE TABLE HOCVIEN
(
	MAHV char(5) PRIMARY KEY,
	HO varchar(40),
	TEN varchar(10),
	NGSINH smalldatetime,
	GIOITINH varchar(3),
	NOISINH varchar(40),
	MALOP char(3) FOREIGN KEY(MALOP) REFERENCES LOP(MALOP)
);

-- GIANGDAY --
CREATE TABLE GIANGDAY
(
	MALOP char(3) FOREIGN KEY(MALOP) REFERENCES LOP(MALOP),
	MAMH varchar(10) FOREIGN KEY(MAMH) REFERENCES MONHOC(MAMH),
	HOCKY tinyint,
	NAM smallint,
	TUNGAY smalldatetime,
	DENNGAY smalldatetime,
	PRIMARY KEY (MALOP, MAMH)
);

-- KETQUATHI --
CREATE TABLE KETQUATHI
(
	MAHV char(5) FOREIGN KEY(MAHV) REFERENCES HOCVIEN(MAHV),
	MAMH varchar(10) FOREIGN KEY(MAMH) REFERENCES MONHOC(MAMH),
	LANTHI tinyint,
	NGTHI smalldatetime,
	DIEM numeric(4,2)
	KQUA varchar(10),
	PRIMARY KEY (MAHV, MAMH)
);



-- BAI TAP 2
-- Sinh viên hoàn thành Phần I bài tập QuanLyBanHang từ câu 2 đến câu 10.
-- 2 --
ALTER TABLE SANPHAM
ADD GHICHU VARCHAR(20);

-- 3 --
ALTER TABLE KHACHHANG
ADD LOAIKH TINYINT;

-- 4 --
ALTER TABLE SANPHAM
ALTER COLUMN GHICHU VARCHAR(100);

-- 5 --
ALTER TABLE SANPHAM
DROP COLUMN GHICHU;

-- 6 --
ALTER TABLE KHACHHANG
ADD LOAIKH VARCHAR(20) CHECK (LOAIKH IN ('Vang lai', 'Thuong xuyen', 'Vip'));

-- 7 --
ALTER TABLE SANPHAM
ADD CONSTRAINT CK_DonViTinh CHECK (DVT IN ('cay', 'hop', 'cai', 'quyen', 'chuc'));

-- 8 --
ALTER TABLE SANPHAM
ADD CONSTRAINT CK_GiaBan CHECK (GIA >= 500);

-- 9 --
ALTER TABLE HOADON
ADD CONSTRAINT CK_SoLuong CHECK (SL > 0);

-- 10 --
ALTER TABLE KHACHHANG
ADD CONSTRAINT CK_NgayDangKy CHECK (NGDK > NGSINH);

-- BAI TAP 3
-- Sinh viên hoàn thành Phần I bài tập QuanLyGiaoVu từ câu 2 đến câu 8.
-- 1 --

ALTER TABLE HOCVIEN
ADD GHICHU NVARCHAR(255),
    DIEMTB FLOAT,
    XEPLOAI NVARCHAR(50);

-- 2 --
CREATE TRIGGER TRG_GenerateMaHV
BEFORE INSERT ON HOCVIEN
FOR EACH ROW
BEGIN
  DECLARE @MaLop CHAR(3);
  DECLARE @SoThuTu INT;
  SET @MaLop = (SELECT MALOP FROM LOP WHERE MALOP = NEW.MALOP);
  SET @SoThuTu = (SELECT ISNULL(MAX(CAST(RIGHT(MAHV, 2) AS INT)), 0) + 1 FROM HOCVIEN WHERE MALOP = @MaLop);
  SET NEW.MAHV = @MaLop + RIGHT('00' + CAST(@SoThuTu AS NVARCHAR(2)), 2);
END;

-- 3 --
ALTER TABLE HOCVIEN
ADD CONSTRAINT CK_GioiTinh CHECK (GIOITINH IN ('Nam', 'Nu'));

-- 4 --
ALTER TABLE KETQUATHI
ADD CONSTRAINT CK_DiemThi CHECK (DIEM >= 0 AND DIEM <= 10);

-- 5 --
ALTER TABLE KETQUATHI
ADD CONSTRAINT CK_KetQuaThi CHECK (KQUA IN ('Dat', 'Khong dat'));

-- 6 --
ALTER TABLE KETQUATHI
ADD CONSTRAINT CK_SoLanThi CHECK (LANTHI >= 1 AND LANTHI <= 3);

-- 7 --
ALTER TABLE GIANGDAY
ADD CONSTRAINT CK_HocKy CHECK (HOCKY >= 1 AND HOCKY <= 3);

-- 8 --
ALTER TABLE GIAOVIEN
ADD CONSTRAINT CK_HocVi CHECK (HOCHAM IN ('CN', 'KS', 'Ths', 'TS', 'PTS'));
