-- 1. Yêu cầu lý thuyết
-- Sinh viên đã được trang bị kiến thức:
-- o Sử dụng truy vấn con.
-- o Sử dụng các câu lệnh hội, giao, trừ, chia.

-- 2. Nội dung
--  Thực hiện được các bài tập sau
-- o Sử dụng truy vấn con để truy vấn dữ liệu trên CSDL Quản lý bán
-- hàng và Quản lý giáo vụ.
-- o Sử dụng các câu lệnh hội, giao, trừ, chia dữ liệu trên CSDL Quản lý
-- bán hàng và Quản lý giáo vụ.

-- BAI TAP 1
-- Sinh viên hoàn thành Phần III bài tập QuanLyBanHang câu 12 và câu 13.
-- 12.	Tìm các số hóa đơn đã mua sản phẩm có mã số “BB01” hoặc “BB02”, mỗi sản phẩm mua với số lượng từ 10 đến 20. -- 
SELECT HOADON.SOHD
FROM HOADON
JOIN CTHD ON HOADON.SOHD = CTHD.SOHD
WHERE CTHD.MASP IN ('BB01', 'BB02')
  AND CTHD.SL BETWEEN 10 AND 20;

-- 13.	Tìm các số hóa đơn mua cùng lúc 2 sản phẩm có mã số “BB01” và “BB02”, mỗi sản phẩm mua với số lượng từ 10 đến 20. --
SELECT HOADON.SOHD
FROM HOADON
JOIN CTHD CTHD1 ON HOADON.SOHD = CTHD1.SOHD
JOIN CTHD CTHD2 ON HOADON.SOHD = CTHD2.SOHD
WHERE CTHD1.MASP = 'BB01' AND CTHD1.SL BETWEEN 10 AND 20
  AND CTHD2.MASP = 'BB02' AND CTHD2.SL BETWEEN 10 AND 20;


-- BAI TAP 2
-- Sinh viên hoàn thành Phần II bài tập QuanLyGiaoVu từ câu 1 đến câu 4.
-- 1 --
UPDATE GIAOVIEN
SET HESO = HESO + 0.2
WHERE MAGV IN (
    SELECT MAGV
    FROM KHOA K
    INNER JOIN GIAOVIEN G ON K.TRGKHOA = G.MAGV
);

-- 2 --
WITH DiemThiSauCung AS (
    SELECT MAHV, MAMH, MAX(LANTHI) AS LANTHI, DIEM
    FROM KETQUATHI
    GROUP BY MAHV, MAMH
);
UPDATE HOCVIEN
SET DIEMTB = (
    SELECT AVG(DIEM)
    FROM DiemThiSauCung D
    WHERE HOCVIEN.MAHV = D.MAHV
);

-- 3 --
WITH DiemThiLan3Duoi5 AS (
    SELECT MAHV, MAMH
    FROM KETQUATHI
    WHERE LANTHI = 3 AND DIEM < 5
);
UPDATE HOCVIEN
SET GHICHU = 'Cam thi'
WHERE MAHV IN (
    SELECT MAHV
    FROM DiemThiLan3Duoi5
);

-- 4 --
UPDATE HOCVIEN
SET XEPLOAI = 
    CASE
        WHEN DIEMTB >= 9 THEN 'XS'
        WHEN DIEMTB >= 8 AND DIEMTB < 9 THEN 'G'
        WHEN DIEMTB >= 6.5 AND DIEMTB < 8 THEN 'K'
        WHEN DIEMTB >= 5 AND DIEMTB < 6.5 THEN 'TB'
        ELSE 'Y'
    END;

-- BAI TAP 3
-- Sinh viên hoàn thành Phần III bài tập QuanLyGiaoVu từ câu 6 đến câu 10.
-- 6 --
SELECT DISTINCT MH.MAMH, MH.TENMH
FROM MONHOC MH
INNER JOIN GIANGDAY GD ON MH.MAMH = GD.MAMH
INNER JOIN GIAOVIEN GV ON GD.MAGV = GV.MAGV
WHERE GV.HOTEN = 'Tran Tam Thanh' AND GD.HOCKY = 1 AND GD.NAM = 2006;

-- 7 --
SELECT DISTINCT MH.MAMH, MH.TENMH
FROM MONHOC MH
INNER JOIN GIANGDAY GD ON MH.MAMH = GD.MAMH
INNER JOIN LOP L ON GD.MALOP = L.MALOP
WHERE L.TENLOP = 'K11' AND GD.HOCKY = 1 AND GD.NAM = 2006;

-- 8 --
SELECT HV.HO, HV.TEN
FROM HOCVIEN HV
INNER JOIN LOP L ON HV.MALOP = L.MALOP
INNER JOIN GIANGDAY GD ON L.MALOP = GD.MALOP
INNER JOIN GIAOVIEN GV ON GD.MAGV = GV.MAGV
INNER JOIN MONHOC MH ON GD.MAMH = MH.MAMH
WHERE GV.HOTEN = 'Nguyen To Lan' AND MH.TENMH = 'Co so du lieu' AND L.TRGLOP = HV.MAHV;

-- 9 --
SELECT MH.MAMH, MH.TENMH
FROM MONHOC MH
INNER JOIN DIEUKIEN DK ON MH.MAMH = DK.MAMH_TRUOC
WHERE DK.MAMH = (SELECT MAMH FROM MONHOC WHERE TENMH = 'Co so du lieu');

-- 10 --
SELECT MH.MAMH, MH.TENMH
FROM MONHOC MH
INNER JOIN DIEUKIEN DK ON MH.MAMH = DK.MAMH_TRUOC
WHERE DK.MAMH_TRUOC = (SELECT MAMH FROM MONHOC WHERE TENMH = 'Cau truc roi rac');

-- BAI TAP 4
-- Sinh viên hoàn thành Phần III bài tập QuanLyBanHang từ câu 14 đến 19.
-- 14.	In ra danh sách các sản phẩm (MASP,TENSP) do “Trung Quoc” sản xuất hoặc các sản phẩm được bán ra trong ngày 1/1/2007. -- 
SELECT MASP, TENSP
FROM SANPHAM1
WHERE NUOCSX = 'Trung Quoc'
   OR MASP IN (SELECT DISTINCT MASP FROM CTHD JOIN HOADON ON CTHD.SOHD = HOADON.SOHD WHERE NGAYBAN = '2007-01-01');

-- 15.	In ra danh sách các sản phẩm (MASP,TENSP) không bán được. -- 
SELECT MASP, TENSP
FROM SANPHAM1
WHERE MASP NOT IN (SELECT DISTINCT MASP FROM CTHD);

-- 16.	In ra danh sách các sản phẩm (MASP,TENSP) không bán được trong năm 2006.
SELECT MASP, TENSP
FROM SANPHAM1
WHERE MASP NOT IN (SELECT DISTINCT MASP FROM CTHD JOIN HOADON ON CTHD.SOHD = HOADON.SOHD WHERE YEAR(NGAYBAN) = 2006);

-- 17.	In ra danh sách các sản phẩm (MASP,TENSP) do “Trung Quoc” sản xuất không bán được trong năm 2006.
SELECT MASP, TENSP
FROM SANPHAM1
WHERE NUOCSX = 'Trung Quoc' AND MASP NOT IN (SELECT DISTINCT MASP FROM CTHD JOIN HOADON ON CTHD.SOHD = HOADON.SOHD WHERE YEAR(NGAYBAN) = 2006);

-- 18.	Tìm số hóa đơn đã mua tất cả các sản phẩm do Singapore sản xuất.
SELECT HOADON.SOHD
FROM HOADON
JOIN CTHD ON HOADON.SOHD = CTHD.SOHD
WHERE CTHD.MASP NOT IN (SELECT DISTINCT MASP FROM SANPHAM1 WHERE NUOCSX <> 'Singapore');

-- 19.	Tìm số hóa đơn trong năm 2006 đã mua ít nhất tất cả các sản phẩm do Singapore sản xuất.
SELECT HOADON.SOHD
FROM HOADON
JOIN CTHD ON HOADON.SOHD = CTHD.SOHD
WHERE YEAR(NGAYBAN) = 2006
GROUP BY HOADON.SOHD
HAVING COUNT(DISTINCT CTHD.MASP) = (SELECT COUNT(DISTINCT MASP) FROM SANPHAM1 WHERE NUOCSX = 'Singapore');


-- BAI TAP 5
-- Sinh viên hoàn thành Phần III bài tập QuanLyGiaoVu từ câu 11 đến câu 18.
-- 11 --
SELECT DISTINCT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
INNER JOIN GIANGDAY GD ON GV.MAGV = GD.MAGV
INNER JOIN MONHOC MH ON GD.MAMH = MH.MAMH
INNER JOIN LOP L ON GD.MALOP = L.MALOP
WHERE MH.TENMH = 'CTRR' AND GD.HOCKY = 1 AND GD.NAM = 2006
  AND L.TENLOP IN ('K11', 'K12');

-- 12 --
SELECT HV.MAHV, HV.HO, HV.TEN
FROM HOCVIEN HV
INNER JOIN KETQUATHI KT ON HV.MAHV = KT.MAHV
INNER JOIN MONHOC MH ON KT.MAMH = MH.MAMH
WHERE MH.TENMH = 'CSDL' AND KT.LANTHI = 1 AND KT.KQUA = 'Khong Dat'
  AND HV.MAHV NOT IN (
    SELECT MAHV
    FROM KETQUATHI
    WHERE MAMH = MH.MAMH AND LANTHI > 1
  );

-- 13 --
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
LEFT JOIN GIANGDAY GD ON GV.MAGV = GD.MAGV
WHERE GD.MAGV IS NULL;

-- 14 --
SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
INNER JOIN KHOA K ON GV.MAKHOA = K.MAKHOA
LEFT JOIN GIANGDAY GD ON GV.MAGV = GD.MAGV
WHERE GD.MAGV IS NULL AND GD.MAKHOA = K.MAKHOA;

-- 15 --
SELECT HV.MAHV, HV.HO, HV.TEN
FROM HOCVIEN HV
INNER JOIN LOP L ON HV.MALOP = L.MALOP
INNER JOIN KETQUATHI KT ON HV.MAHV = KT.MAHV
INNER JOIN MONHOC MH ON KT.MAMH = MH.MAMH
WHERE L.TENLOP = 'K11' AND (
  (KT.LANTHI > 3 AND KT.KQUA = 'Khong Dat')
  OR (KT.LANTHI = 2 AND MH.TENMH = 'CTRR' AND KT.DIEM = 5)
);

-- 16 --
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN GV
INNER JOIN GIANGDAY GD ON GV.MAGV = GD.MAGV
INNER JOIN MONHOC MH ON GD.MAMH = MH.MAMH
WHERE MH.TENMH = 'CTRR'
GROUP BY GV.HOTEN, GD.HOCKY, GD.NAM
HAVING COUNT(DISTINCT GD.MALOP) >= 2;

-- 17 --
SELECT HV.MAHV, HV.HO, HV.TEN, KT.LANTHI, KT.DIEM
FROM HOCVIEN HV
INNER JOIN KETQUATHI KT ON HV.MAHV = KT.MAHV
INNER JOIN MONHOC MH ON KT.MAMH = MH.MAMH
WHERE MH.TENMH = 'CSDL'
  AND (KT.MAMH, KT.MAHV, KT.LANTHI) IN (
    SELECT MAMH, MAHV, MAX(LANTHI)
    FROM KETQUATHI
    GROUP BY MAMH, MAHV
  );

-- 18 --
SELECT HV.MAHV, HV.HO, HV.TEN, MAX(KT.DIEM) AS DIEM
FROM HOCVIEN HV
INNER JOIN KETQUATHI KT ON HV.MAHV = KT.MAHV
INNER JOIN MONHOC MH ON KT.MAMH = MH.MAMH
WHERE MH.TENMH = 'Co so du Lieu'
GROUP BY HV.MAHV, HV.HO, HV.TEN;
