-- 1. Yêu cầu lý thuyết
-- Sinh viên đã được trang bị kiến thức:
-- o Sử dụng các câu lệnh tính toán, gom nhóm

-- 2. Nội dung
--  Thực hiện được các bài tập sau
-- o Sử dụng các câu lệnh tính toán, gom nhóm dữ liệu trên CSDL Quản
-- lý bán hàng và Quản lý giáo vụ.

-- BAI TAP 1
-- Sinh viên hoàn thành Phần III bài tập QuanLyBanHang từ câu 20 đến 30.
-- 20.	Có bao nhiêu hóa đơn không phải của khách hàng đăng ký thành viên mua?
SELECT COUNT(DISTINCT SOHD)
FROM HOADON
WHERE MAKH NOT IN (SELECT MAKH FROM KHACHHANG1 WHERE LOAIKH = 'Dang ky thanh vien');

-- 21.	Có bao nhiêu sản phẩm khác nhau được bán ra trong năm 2006.
SELECT COUNT(DISTINCT MASP)
FROM CTHD
JOIN HOADON ON CTHD.SOHD = HOADON.SOHD
WHERE YEAR(NGAYBAN) = 2006;

-- 22.	Cho biết trị giá hóa đơn cao nhất, thấp nhất là bao nhiêu ?
SELECT MAX(TONGTIEN) AS TrigiaCaoNhat, MIN(TONGTIEN) AS TrigiaThapNhat
FROM HOADON;

-- 23.	Trị giá trung bình của tất cả các hóa đơn được bán ra trong năm 2006 là bao nhiêu?
SELECT AVG(TONGTIEN) AS TrigiaTrungBinh
FROM HOADON
WHERE YEAR(NGAYBAN) = 2006;

-- 24.	Tính doanh thu bán hàng trong năm 2006.
SELECT SUM(TONGTIEN) AS DoanhThu
FROM HOADON
WHERE YEAR(NGAYBAN) = 2006;

-- 25.	Tìm số hóa đơn có trị giá cao nhất trong năm 2006.
SELECT SOHD, TONGTIEN
FROM HOADON
WHERE TONGTIEN = (SELECT MAX(TONGTIEN) FROM HOADON WHERE YEAR(NGAYBAN) = 2006);

-- 26.	Tìm họ tên khách hàng đã mua hóa đơn có trị giá cao nhất trong năm 2006.
SELECT KHACHHANG1.HOTEN
FROM KHACHHANG1
JOIN HOADON ON KHACHHANG1.MAKH = HOADON.MAKH
WHERE HOADON.TONGTIEN = (SELECT MAX(TONGTIEN) FROM HOADON WHERE YEAR(NGAYBAN) = 2006);

-- 27.	In ra danh sách 3 khách hàng đầu tiên (MAKH, HOTEN) sắp xếp theo doanh số giảm dần.
SELECT MAKH, HOTEN
FROM KHACHHANG1
ORDER BY (SELECT SUM(TONGTIEN) FROM HOADON WHERE HOADON.MAKH = KHACHHANG1.MAKH) DESC
LIMIT 3;

-- 28.	In ra danh sách các sản phẩm (MASP, TENSP) có giá bán bằng 1 trong 3 mức giá cao nhất.
SELECT MASP, TENSP
FROM SANPHAM1
WHERE GiaBan IN (SELECT DISTINCT GiaBan FROM SANPHAM1 ORDER BY GiaBan DESC LIMIT 3);

-- 29.	In ra danh sách các sản phẩm (MASP, TENSP) do “Thai Lan” sản xuất có giá bằng 1 trong 3 mức giá cao nhất (của tất cả các sản phẩm).
SELECT MASP, TENSP
FROM SANPHAM1
WHERE NUOCSX = 'Thai Lan' 
AND GiaBan IN (
	SELECT DISTINCT GiaBan 
	FROM SANPHAM1 
	WHERE NUOCSX = 'Thai Lan' 
	ORDER BY GiaBan DESC 
	LIMIT 3);

-- 30.	In ra danh sách các sản phẩm (MASP, TENSP) do “Trung Quoc” sản xuất có giá bằng 1 trong 3 mức giá cao nhất (của sản phẩm do “Trung Quoc” sản xuất).
SELECT MASP, TENSP
FROM SANPHAM1
WHERE NUOCSX = 'Trung Quoc' 
AND GiaBan IN (
	SELECT DISTINCT GiaBan 
	FROM SANPHAM1 
	WHERE NUOCSX = 'Trung Quoc' 
	ORDER BY GiaBan DESC 
	LIMIT 3);

-- BAI TAP 2
-- Sinh viên hoàn thành Phần III bài tập QuanLyGiaoVu từ câu 19 đến câu 25.
-- 19 --
SELECT MAKHOA, TENKHOA
FROM KHOA
ORDER BY NGTLAP
LIMIT 1;

-- 20 --
SELECT COUNT(*) AS SoLuong
FROM GIAOVIEN
WHERE HOCHAM IN ('GS', 'PGS');

-- 21 --
SELECT K.MAKHOA, K.TENKHOA, 
       COUNT(CASE WHEN GV.HOCVI IN ('CN', 'KS', 'Ths', 'TS', 'PTS') THEN 1 ELSE NULL END) AS SoLuongGiaoVien
FROM GIAOVIEN GV
INNER JOIN KHOA K ON GV.MAKHOA = K.MAKHOA
GROUP BY K.MAKHOA, K.TENKHOA;

-- 22 --
SELECT MAMH, TENMH,
       SUM(CASE WHEN KQUA = 'Dat' THEN 1 ELSE 0 END) AS SoLuongDat,
       SUM(CASE WHEN KQUA = 'Khong Dat' THEN 1 ELSE 0 END) AS SoLuongKhongDat
FROM KETQUATHI KT
INNER JOIN MONHOC MH ON KT.MAMH = MH.MAMH
GROUP BY MAMH, TENMH;

-- 23 --
SELECT DISTINCT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
INNER JOIN LOP L ON GV.MAGV = L.TRGLOP
INNER JOIN GIANGDAY GD ON GV.MAGV = GD.MAGV
WHERE GD.MALOP = L.MALOP;

-- 24 --
SELECT HV.HO, HV.TEN
FROM HOCVIEN HV
INNER JOIN LOP L ON HV.MAHV = L.TRGLOP
WHERE L.SISO = (
  SELECT MAX(SISO) FROM LOP
);

-- 25 --
SELECT HV.HO, HV.TEN
FROM HOCVIEN HV
INNER JOIN LOP L ON HV.MAHV = L.TRGLOP
WHERE L.MALOP IN (
  SELECT MALOP
  FROM LOP
  WHERE MALOP IN (
    SELECT MALOP
    FROM GIANGDAY GD
    WHERE GD.MAGV = L.TRGLOP
  )
  AND MALOP NOT IN (
    SELECT MALOP
    FROM KETQUATHI KT
    WHERE KQUA = 'Đạt'
    GROUP BY MALOP
    HAVING COUNT(*) >= 3
  )
);

-- BAI TAP 3
-- Sinh viên hoàn thành Phần III bài tập QuanLyBanHang từ câu 31 đến 45.

-- 31.	* In ra danh sách khách hàng nằm trong 3 hạng cao nhất (xếp hạng theo doanh số).
SELECT KHACHHANG1.MAKH, KHACHHANG1.HOTEN
FROM KHACHHANG1
JOIN HOADON ON KHACHHANG1.MAKH = HOADON.MAKH
GROUP BY KHACHHANG1.MAKH, KHACHHANG1.HOTEN
ORDER BY SUM(HOADON.TONGTIEN) DESC
LIMIT 3;

-- 32.	Tính tổng số sản phẩm do “Trung Quoc” sản xuất.
SELECT COUNT(MASP) AS TongSanPhamTrungQuoc
FROM SANPHAM1
WHERE NUOCSX = 'Trung Quoc';

-- 33.	Tính tổng số sản phẩm của từng nước sản xuất.
SELECT NUOCSX, COUNT(MASP) AS TongSanPham
FROM SANPHAM1
GROUP BY NUOCSX;

-- 34.	Với từng nước sản xuất, tìm giá bán cao nhất, thấp nhất, trung bình của các sản phẩm.
SELECT NUOCSX, MAX(GiaBan) AS GiaBanCaoNhat, MIN(GiaBan) AS GiaBanThapNhat, AVG(GiaBan) AS GiaBanTrungBinh
FROM SANPHAM1
GROUP BY NUOCSX;

-- 35.	Tính doanh thu bán hàng mỗi ngày.
SELECT NGAYBAN, SUM(TONGTIEN) AS DoanhThu
FROM HOADON
GROUP BY NGAYBAN;

-- 36.	Tính tổng số lượng của từng sản phẩm bán ra trong tháng 10/2006.
SELECT CTHD.MASP, SANPHAM1.TENSP, SUM(CTHD.SL) AS TongSoLuong
FROM CTHD
JOIN SANPHAM1 ON CTHD.MASP = SANPHAM1.MASP
JOIN HOADON ON CTHD.SOHD = HOADON.SOHD
WHERE YEAR(NGAYBAN) = 2006 AND MONTH(NGAYBAN) = 10
GROUP BY CTHD.MASP, SANPHAM1.TENSP;

-- 37.	Tính doanh thu bán hàng của từng tháng trong năm 2006.
SELECT MONTH(NGAYBAN) AS Thang, SUM(TONGTIEN) AS DoanhThu
FROM HOADON
WHERE YEAR(NGAYBAN) = 2006
GROUP BY MONTH(NGAYBAN);

-- 38.	Tìm hóa đơn có mua ít nhất 4 sản phẩm khác nhau.
SELECT SOHD
FROM CTHD
GROUP BY SOHD
HAVING COUNT(DISTINCT MASP) >= 4;

-- 39.	Tìm hóa đơn có mua 3 sản phẩm do “Viet Nam” sản xuất (3 sản phẩm khác nhau).
SELECT HOADON.SOHD
FROM HOADON
JOIN CTHD ON HOADON.SOHD = CTHD.SOHD
JOIN SANPHAM1 ON CTHD.MASP = SANPHAM1.MASP
WHERE NUOCSX = 'Viet Nam'
GROUP BY HOADON.SOHD
HAVING COUNT(DISTINCT CTHD.MASP) = 3;

-- 40.	Tìm khách hàng (MAKH, HOTEN) có số lần mua hàng nhiều nhất.
SELECT MAKH, HOTEN
FROM KHACHHANG1
WHERE MAKH IN (SELECT MAKH FROM HOADON GROUP BY MAKH ORDER BY COUNT(*) DESC LIMIT 1);

-- 41.	Tháng mấy trong năm 2006, doanh số bán hàng cao nhất ?
SELECT MONTH(NGAYBAN) AS Thang, SUM(TONGTIEN) AS DoanhSo
FROM HOADON
WHERE YEAR(NGAYBAN) = 2006
GROUP BY MONTH(NGAYBAN)
ORDER BY SUM(TONGTIEN) DESC
LIMIT 1;

-- 42.	Tìm sản phẩm (MASP, TENSP) có tổng số lượng bán ra thấp nhất trong năm 2006.
SELECT CTHD.MASP, SANPHAM1.TENSP, SUM(CTHD.SL) AS TongSoLuong
FROM CTHD
JOIN SANPHAM1 ON CTHD.MASP = SANPHAM1.MASP
JOIN HOADON ON CTHD.SOHD = HOADON.SOHD
WHERE YEAR(NGAYBAN) = 2006
GROUP BY CTHD.MASP, SANPHAM1.TENSP
ORDER BY TongSoLuong
LIMIT 1;

-- 43.	*Mỗi nước sản xuất, tìm sản phẩm (MASP,TENSP) có giá bán cao nhất.
SELECT NUOCSX, MASP, TENSP, GiaBan
FROM SANPHAM1
WHERE (NUOCSX, GiaBan) IN (SELECT NUOCSX, MAX(GiaBan) FROM SANPHAM1 GROUP BY NUOCSX);

-- 44.	Tìm nước sản xuất sản xuất ít nhất 3 sản phẩm có giá bán khác nhau.
SELECT NUOCSX
FROM SANPHAM1
GROUP BY NUOCSX
HAVING COUNT(DISTINCT GiaBan) >= 3;

-- 45.	*Trong 10 khách hàng có doanh số cao nhất, tìm khách hàng có số lần mua hàng nhiều nhất.
SELECT KHACHHANG1.MAKH, KHACHHANG1.HOTEN, COUNT(HOADON.MAKH) AS SoLanMua
FROM KHACHHANG1
JOIN HOADON ON KHACHHANG1.MAKH = HOADON.MAKH
WHERE KHACHHANG1.MAKH IN (SELECT MAKH FROM HOADON GROUP BY MAKH ORDER BY SUM(TONGTIEN) DESC LIMIT 10)
GROUP BY KHACHHANG1.MAKH, KHACHHANG1.HOTEN
ORDER BY SoLanMua DESC
LIMIT 1;

-- BAI TAP 4
-- Sinh viên hoàn thành Phần III bài tập QuanLyGiaoVu từ câu 26 đến câu 35.
-- 26 --
SELECT HV.MAHV, HV.HO, HV.TEN
FROM HOCVIEN HV
INNER JOIN KETQUATHI KT ON HV.MAHV = KT.MAHV
WHERE KT.DIEM >= 9
GROUP BY HV.MAHV, HV.HO, HV.TEN
HAVING COUNT(KT.MAMH) = (
  SELECT MAX(TongMonDat)
  FROM (
    SELECT MAHV, COUNT(MAMH) AS TongMonDat
    FROM KETQUATHI
    WHERE DIEM >= 9
    GROUP BY MAHV
  ) AS Temp
);

-- 27 --
SELECT L.MALOP, HV.MAHV, HV.HO, HV.TEN
FROM LOP L
INNER JOIN HOCVIEN HV ON L.TRGLOP = HV.MAHV
INNER JOIN KETQUATHI KT ON HV.MAHV = KT.MAHV
WHERE KT.DIEM >= 9
GROUP BY L.MALOP, HV.MAHV, HV.HO, HV.TEN
HAVING COUNT(KT.MAMH) = (
  SELECT MAX(TongMonDat)
  FROM (
    SELECT MALOP, MAHV, COUNT(MAMH) AS TongMonDat
    FROM KETQUATHI KT2
    WHERE DIEM >= 9
    GROUP BY MALOP, MAHV
  ) AS Temp
  WHERE Temp.MALOP = L.MALOP
);

-- 28 --
SELECT GD.HOCKY, GD.NAM, GD.MAGV, GV.HOTEN,
       COUNT(DISTINCT GD.MAMH) AS SoMonHoc,
       COUNT(DISTINCT GD.MALOP) AS SoLop
FROM GIANGDAY GD
INNER JOIN GIAOVIEN GV ON GD.MAGV = GV.MAGV
GROUP BY GD.HOCKY, GD.NAM, GD.MAGV, GV.HOTEN;

-- 29 --
SELECT GD.HOCKY, GD.NAM, GD.MAGV, GV.HOTEN
FROM GIANGDAY GD
INNER JOIN GIAOVIEN GV ON GD.MAGV = GV.MAGV
GROUP BY GD.HOCKY, GD.NAM, GD.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT GD.MAMH) = (
  SELECT MAX(SoMonHoc)
  FROM (
    SELECT HOCKY, NAM, MAGV, COUNT(DISTINCT MAMH) AS SoMonHoc
    FROM GIANGDAY
    GROUP BY HOCKY, NAM, MAGV
  ) AS Temp
  WHERE Temp.HOCKY = GD.HOCKY AND Temp.NAM = GD.NAM
);

-- 30 --
SELECT MH.MAMH, MH.TENMH
FROM MONHOC MH
INNER JOIN KETQUATHI KT ON MH.MAMH = KT.MAMH
WHERE KT.LANTHI = 1 AND KT.KQUA = 'Khong Dat'
GROUP BY MH.MAMH, MH.TENMH
ORDER BY COUNT(KT.MAHV) DESC
LIMIT 1;

-- 31 --
SELECT HV.MAHV, HV.HO, HV.TEN
FROM HOCVIEN HV
WHERE HV.MAHV NOT IN (
  SELECT KT.MAHV
  FROM KETQUATHI KT
  WHERE KT.LANTHI = 1 AND KT.KQUA = 'Khong Dat'
);

-- 32 --
SELECT HV.MAHV, HV.HO, HV.TEN
FROM HOCVIEN HV
WHERE HV.MAHV NOT IN (
  SELECT KT.MAHV
  FROM KETQUATHI KT
  WHERE KT.LANTHI = (
    SELECT MAX(LANTHI)
    FROM KETQUATHI
    WHERE MAHV = HV.MAHV
  ) AND KT.KQUA = 'Khong Dat'
);

-- 33 --
SELECT HV.MAHV, HV.HO, HV.TEN
FROM HOCVIEN HV
WHERE HV.MAHV IN (
  SELECT MAHV
  FROM MONHOC MH
  WHERE NOT EXISTS (
    SELECT MAMH
    FROM MONHOC
    WHERE NOT EXISTS (
      SELECT KT.MAHV
      FROM KETQUATHI KT
      WHERE KT.MAMH = MH.MAMH AND KT.LANTHI = 1 AND KT.MAHV = HV.MAHV AND KT.KQUA = 'Khong Dat'
    )
  )
);

-- 34 --
SELECT HV.MAHV, HV.HO, HV.TEN
FROM HOCVIEN HV
WHERE HV.MAHV IN (
  SELECT MAHV
  FROM MONHOC MH
  WHERE NOT EXISTS (
    SELECT MAMH
    FROM MONHOC
    WHERE NOT EXISTS (
      SELECT KT.MAHV
      FROM KETQUATHI KT
      WHERE KT.MAMH = MH.MAMH AND KT.LANTHI = (
        SELECT MAX(LANTHI)
        FROM KETQUATHI
        WHERE MAMH = MH.MAMH AND MAHV = HV.MAHV
      ) AND KT.MAHV = HV.MAHV AND KT.KQUA = 'Khong Dat'
    )
  )
);

-- 35 --
SELECT KT1.MAHV, HV.HO, HV.TEN, KT1.MAMH, MH.TENMH, KT1.DIEM
FROM KETQUATHI KT1
INNER JOIN HOCVIEN HV ON KT1.MAHV = HV.MAHV
INNER JOIN MONHOC MH ON KT1.MAMH = MH.MAMH
WHERE KT1.LANTHI = (
  SELECT MAX(LANTHI)
  FROM KETQUATHI KT2
  WHERE KT1.MAHV = KT2.MAHV AND KT1.MAMH = KT2.MAMH
)
AND KT1.DIEM = (
  SELECT MAX(DIEM)
  FROM KETQUATHI KT3
  WHERE KT1.MAHV = KT3.MAHV AND KT1.MAMH = KT3.MAMH AND KT1.LANTHI = KT3.LANTHI
)
GROUP BY KT1.MAHV, HV.HO, HV.TEN, KT1.MAMH, MH.TENMH, KT1.DIEM;


