CREATE DATABASE QLDDH;
USE QLDDH;

CREATE TABLE MATHANG
(
	MAMH char(6) PRIMARY KEY,
	TENMH varchar(100),
	DVT varchar(20),
	NUOCSX varchar(40)
)

CREATE TABLE NHACC
(
	MACC char(4) PRIMARY KEY,
	TENCC varchar(100),
	DIACHICC varchar(200)
)

CREATE TABLE CUNGCAP
(
	MACC char(4) FOREIGN KEY REFERENCES NHACC(MACC),
	MAMH char(6) FOREIGN KEY REFERENCES MATHANG(MAMH),
	TUNGAY smalldatetime,
	PRIMARY KEY (MACC, MAMH)
)

CREATE TABLE DONDH
(
	MADH int PRIMARY KEY,
	NGAYDH smalldatetime,
	MACC char(4) FOREIGN KEY REFERENCES NHACC(MACC),
	TONGTRIGIA money,
	SOMH int
)

CREATE TABLE CHITIET
(
	MADH int FOREIGN KEY REFERENCES DONDH(MADH),
	MAMH char(6) FOREIGN KEY REFERENCES MATHANG(MAMH),
	SOLUONG int,
	DONGIA money,
	TRIGIA money,
	PRIMARY KEY (MADH, MAMH)
)

-- 2 --
SELECT *
FROM DONDH
JOIN NHACC ON DONDH.MACC = NHACC.MACC
WHERE NHACC.TENCC = 'DOTB' 
AND DONDH.TONGTRIGIA > 1000000;

-- 3 --
SELECT NHACC.MACC, NHACC.TENCC, CUNGCAP.TUNGAY
FROM NHACC
JOIN CUNGCAP ON NHACC.MACC = CUNGCAP.MACC
WHERE CUNGCAP.MAMH = 'MH0001' 
AND CUNGCAP.TUNGAY > '2018-01-01';

-- 4 --
SELECT NHACC.MACC, NHACC.TENCC
FROM NHACC
LEFT JOIN DONDH ON NHACC.MACC = DONDH.MACC
WHERE DONDH.MACC IS NULL;

-- 5 --
SELECT NHACC.MACC, NHACC.TENCC
FROM NHACC
INNER JOIN CUNGCAP ON NHACC.MACC = CUNGCAP.MACC
INNER JOIN MATHANG ON CUNGCAP.MAMH = MATHANG.MAMH
WHERE MATHANG.NUOCSX = 'Việt Nam'
GROUP BY NHACC.MACC, NHACC.TENCC
HAVING COUNT(DISTINCT CUNGCAP.MAMH) = (SELECT COUNT(*) FROM MATHANG WHERE NUOCSX = 'Việt Nam');